### ISSUE TITLE
Dialog window hides behind the main O window

### ISSUE THREAD

**Issue by ghost** [scadaperspective/Simulator_pi#5]
More often than not, if one is moving or clicking elsewhere in O main windows, or on another open dialog, Simulator_pi dialog moves itself on the bottom of the stack, behind the main O window. This can be resolved in two ways: by deactivating/activating from toolbar, or from Windows toolbar, from which one can pick up the dialog up again. Sometimes it stays in the front better, sometimes not, cannot detect a pattern for that.

**Comment by ghost** [comment]
I took this Rick's 2019-07-01 commit  https://github.com/rgleason/Simulator_pi/commit/f517307c63565767b988301867d46c3bbad41f1d 
built artefact from AppVeoyr  - I confirm the behavior  described in the opening of this ticket being persistent.
I synced to upstream, downloaded and build on both my local systems, Win10 and Ubuntu 16.04LTS. Same result: window is an independent window from the OpenCPN main window and thus can be hidden by the OpenCPN window when one clicks on it somewhere.

**Comment by ghost** [comment]
This makes me thing that maybe we have different understanding of 

> wxFRAME_FLOAT_ON_PARENT:
> The frame will always be on top of its parent (unlike wxSTAY_ON_TOP). A frame created with this style must have a non-NULL parent.
https://docs.wxwidgets.org/stable/classwx_frame.html

which is declared in Simulatorgui.h - by wxFormBuilder.

If the intended behavior is that of a free window frame, this issue is not an issue, please close it.

**Comment by ghost** [comment]
But if the intended behavior is that of a modal window https://en.wikipedia.org/wiki/Modal_window , such as a dialog wxDialog, then one can study if the wxFormBuilder allows to define the base class to be wxDialog instead of wxFrame, as it is today.

**Comment by ghost** [comment]
In fact, may people have, apparently, attempted to make a wxFrame modal (search "wxwidgets create a modal frame")  some with more success than others but always by creating their own derived class from wxFrame.

**Comment by scadaperspective** [comment]
I will have a look at the formbuilder and see if the frame types  are selectable.

**Comment by scadaperspective** [comment]
Petri

Pondering here atm before getting in front of the computers. 

It is highly probable that formbuilder has set the frame type to a default it seems to do that with other elements for example if you move them for example. 

Once i am in the office today I will check the frame related settings for each frame i have created and see if it has set something to a floating type. 

 Also what version of linux are you using , I have compiled my own version of wxWidgets 3.1.2 so that the platform is compliant with the prerequisites for the package. The pre install libraries use 3.0.4 on ubuntu studio 19.04 for example. 

I can find the config for compiling it that David suggested if you need it maybe that is why i’m not seeing the problem. 
It is only logical to me that it causes problems mixing dependant libraries it did on my machine until I changed the libraries.

**Comment by ghost** [comment]
If wxFormBuilder is using wxFrame window for a dialog, they must have the modal function built in the generated code. That is, they are providing the same functionality than wxDialog class provides in hand written code. Which is fine. Provided it works cross-platform. Let's see.

**Comment by rgleason** [comment]
> Once you have the Simulator dialog in view and in front of all windows and you click anywhere on the OpenCPN canvas which is behind, what happens?

The simulator window hides behind when I click anywhere else in the screen.
Also the simulator "wheel" icon reverts to "TP" at some point here.

**Comment by ghost** [comment]
_Voilà_! See above the definition of wxFRAME_FLOAT_ON_PARENT which is declared by wxFormBuilder for the base class which is wxFrame. We both confirm, therefore that the behavior in Windows (+ Linux for me) is not as it is declared in the documentation of this window style attribute or for a modal dialog window in general.

**Comment by ghost** [comment]
For the record, Linux is out of the box 16.04 LTS without any purpose installed developers or other version of wxWidget, installed with distribution's OpenCPN v5.0.

**Comment by scadaperspective** [comment]
Looked at several other plugins and they all are configured differently. Happy to amend frame options to some sort of documented standard.
