### ISSUE TITLE
Degree sign on Windows is not shown - encoding broken

### ISSUE THREAD

**Issue by ghost** [scadaperspective/Simulator_pi#6]
Everywhere in the dialog where there is a degree sign, on Windows it is encoded wrongly. I know that, traditionally it is resolved in OpenCPN programs as _T("\u00B0") macro, but knowing that this deprecated since years, that is not a good idea, perhaps. On the other hand, we can see that on Mac and Windows this does not cause a problem, maybe it can be fixed by showing on Windows only "\u00B0", without a _T() wxWidgets macro, cf. [Unicode degree sign](http://www.fileformat.info/info/unicode/char/b0/index.htm)

**Comment by scadaperspective** [comment]
Will leave one issue open for special chrs until I can work out a method that is cross platform compliant.
