### ISSUE TITLE
+/- sign special character does not show on Windows.

### ISSUE THREAD

**Issue by ghost** [scadaperspective/Simulator_pi#7]
In static tab:
<img width="215" alt="2019-07-02_214059_plus-minus_static" src="https://user-images.githubusercontent.com/6381128/60549121-354af880-9d24-11e9-9d66-5357732b3a12.png">
It shows OK on Linux:
<img width="214" alt="2019-07-02_214821_plus-minus_static_OK_ubuntu_1604lts" src="https://user-images.githubusercontent.com/6381128/60549134-3f6cf700-9d24-11e9-9ea5-9f49ce998a02.png">

**Comment by scadaperspective** [comment]
Yes linux seems ok with special characters generally wxwidgets is more unicode compatible

**Comment by scadaperspective** [comment]
More Cross platform unicode fun.
