### ISSUE TITLE
Starting Static on Linux does not show the same indicator as on Windows

### ISSUE THREAD

**Issue by ghost** [scadaperspective/Simulator_pi#8]
On Windows it looks like this:
<img width="340" alt="2019-07-02_214450_Static_drive_win" src="https://user-images.githubusercontent.com/6381128/60549275-aab6c900-9d24-11e9-8924-4897a353c41b.png">
On Linux (Ubuntu 16.04 LTS) like this:
<img width="345" alt="2019-07-02 _214944_Static_drive_ubuntu_1604lts" src="https://user-images.githubusercontent.com/6381128/60549299-bbffd580-9d24-11e9-9d15-6d0e642df4b4.png">

**Comment by scadaperspective** [comment]
So here you go  your using standard repo's and wx widgets is not 3.1.2 :) More likely 3.0.4 ???

I will drag out my linux box after I make a coffee and have something to eat only just back in the office now :)

**Comment by ghost** [comment]
Absolute standard out of the box installation on Ubuntu 16.04 LTS as any user would have (they do not tweak with the wxWidgets version, you know...). I'll be out to office, for traveling, so I won't be able to retest this on the same system before 10 days from now; maybe you can install a VM on Mac for validation of this..

**Comment by scadaperspective** [comment]
Hi Petri

Travel safe 

in the time your away I will sort out a windows env to test fairly confident it will be the reason just the same.

I have a theory re Linux after all the trouble i had with compiling the wxWidgets library a good one to tell over a few drinks.

Short version is how many programmers do you come across in life that you truly know they need to learn people skills ? 

I had no end of trouble on linux and macOS with wx and with Xcode, all sorted now. 



/Ron

**Comment by scadaperspective** [comment]
NAS finally arrived today so a week or so of backings to queue 

Windows OS sorted out once backups are completed and verified.
