### ISSUE TITLE
On Windows the installer installs Simulator as full-blown windows application

### ISSUE THREAD

**Issue by ghost** [scadaperspective/Simulator_pi#9]
Unlike the other OpenCPN plugins, which merely put the uninstaller it the Program directory of OpenCPN, Simulator_pi installer on windows creates an entry which shows on Windows Apps and Features.
<img width="410" alt="2019-07-02_214620_Simulator_appears_as_Windows_program_in_Apps_n_Features" src="https://user-images.githubusercontent.com/6381128/60549456-30d30f80-9d25-11e9-86a8-d49e747597c2.png">
I don't mark this as bug since I do not have a notion which is the instructions from OpenCPN developers for this. I just notice that this the first plugin in ov50 which has this behavior.

**Comment by scadaperspective** [comment]
Has to be something to do with form builder defaults :) 

Just checked the frame type for what is happening on windows... 

The default is for it to be disabled of course  ! At some point the frame has defaulted to not being on top.

**Comment by scadaperspective** [comment]
Hi Petri

 this I hope should make things a little easier WR2 staying on top 
-  no need to look any further I hope ...

Selected stay on top on FormBuilder for all the frames that are in the xml project and re-generated source. No impact on macOS.. It has changed at some stage, something to check on if I make any substantive changes to the GUI.

Also de-selected wxSYSTEM_MENU which was enabled as well, to see if the plugin is no longer seen as a stand alone program.  Not so confident that this is the culprit but it is a point to start from.

**Comment by rgleason** [comment]
When I open Simulator there is a duplicate Opencpn Icon made in the taskbar. When the always on top menu disappears behind the full program. I can click on the second icon. It often goes behind again. Then I click again and it will stay in front.

**Comment by ghost** [comment]
Once you have the Simulator dialog in view and in front of all windows and you click anywhere on the OpenCPN canvas which is behind, what happens?

**Comment by ghost** [comment]
Actually, let's continue the discussion about the modal window behavior in #5 it belongs there. This issue is about the installer - Rick, do you know is there a OpenCPN design guideline regarding the installer / uninstaller required features for plugins in Windows or is it anybody does what they want?

**Comment by rgleason** [comment]
The installer/uninstaller is actually just built for Windows by the NSIS package. Pavel would know more about the inner workings I believe.  The uninstaller.exe is packaged by nsis and installed when the plugin is installed on the users machine, obviously.

**Comment by ghost** [comment]
I took Sean's and it does not have this behavior.

**Comment by ghost** [comment]
The question is, what does OpenCPN want?

**Comment by ghost** [comment]
Or, maybe they do not care?

**Comment by rgleason** [comment]
I would expect Simulator to behave largely in parallel with the other plugins.
I find no simulator uninstall exe in the 

C:\Program Files (x86)\[OpenCPN 5.0.0+20c9a05]  directory.
![Screenshot (228)](https://user-images.githubusercontent.com/2363959/60589343-45d09280-9d67-11e9-9bd6-eed5ed844b55.png)

**Comment by ghost** [comment]
This was my point.

**Comment by scadaperspective** [comment]
A windows OS issue .....

will sort out once I have a working windows machine and compiler environment to be able to test code changes with.
